# Enable Split support
CONFIG_ZMK_SPLIT=y

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Turn on logging
CONFIG_ZMK_USB_LOGGING=y
# Optional: finer detail for matrix debugging
CONFIG_ZMK_LOG_LEVEL_DBG=y